# Generated by Django 4.1.13 on 2024-08-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Restauro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'restauros',
            },
        ),
        migrations.CreateModel(
            name='TipoMaoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('custo_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tipos_mao_obra',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cliente')),
            ],
            options={
                'db_table': 'veiculos',
            },
        ),
        migrations.CreateModel(
            name='TarefaRestauro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('mao_obra', models.CharField(max_length=100)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restauro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restauro')),
            ],
            options={
                'db_table': 'tarefas_restauro',
            },
        ),
        migrations.CreateModel(
            name='SaidaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField()),
                ('condicoes_saida', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.veiculo')),
            ],
            options={
                'db_table': 'saidas_veiculos',
            },
        ),
        migrations.AddField(
            model_name='restauro',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.veiculo'),
        ),
        migrations.CreateModel(
            name='RegistoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.veiculo')),
            ],
            options={
                'db_table': 'registo_entradas',
            },
        ),
        migrations.CreateModel(
            name='Faturacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itens', models.TextField(blank=True, null=True)),
                ('status_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('restauro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restauro')),
            ],
            options={
                'db_table': 'faturacao',
            },
        ),
    ]
