# Generated by Django 4.1.13 on 2024-08-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cliente_restauro_tipomaoobra_veiculo_tarefarestauro_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='veiculo',
            table=None,
        ),
    ]
